#!/bin/bash
#for loop with &&'s and ||'s

for x in {1..100};
do
        { (( x % 5 == 0 )) && (( x % 3 == 0 )) &&  echo "$x fizzbuzz"; } || 
        { (( x % 5 == 0 )) && echo "$x buzz"; } || 
        { (( x % 3 == 0 )) && echo "$x fizz"; } ||

                echo "$x"

done

#while loop with if's and then's

(( x=1 ));
while (( x < 101 ));
do

        if { ( (( x % 5 == 0 )) && (( x % 3 == 0 )) ) } then echo "fizzbuzz";
        elif    (( x % 5 == 0 ));  then echo "buzz";
        elif    (( x % 3 == 0 ));  then echo "fizz";
        else
                echo "$x";
        fi

(( x++ ))

done

